[package]
name = "orc-rust"
version = "0.2.41"
edition = "2021"
homepage = "https://github.com/wenyxu/orc-rs"
repository = "https://github.com/wenyxu/orc-rs"
authors = ["Weny <wenymedia@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Yet another unofficial implementation of Apache ORC spec in safe Rust"
keywords = ["arrow", "orc", "arrow-rs"]
include = ["src/**/*.rs", "Cargo.toml"]
rust-version = "1.70"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = { version = "43.0", features = ["prettyprint"] }
bytes = "1.4"
chrono = "0.4"
flate2 = "1"
fallible-streaming-iterator = { version = "0.1" }
paste = "1.0"
prost = { version = "0.11" }
lazy_static = "1.4"
snafu = "0.7"
zigzag = "0.1"
tokio = { version = "1.28", features = [
    "io-util",
    "sync",
    "fs",
    "macros",
    "rt",
] }
futures = { version = "0.3", default-features = false, features = ["std"] }
futures-util = "0.3"
zstd = "0.12"
