[package]
name = "orc-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = "42.0.0"
bytes = "1.4"
chrono = "0.4.26"
flate2 = "1"
fallible-streaming-iterator = { version = "0.1" }
paste = "1.0.12"
prost = { version = "0.11.9" }
lazy_static = "1.4.0"
snafu = "0.7.4"
